name: build-test-deploy

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Build Next.js app
      - name: Build Next.js app
        run: npm run build

      # Step 5: Copy static files for deployment
      - name: Prepare static build for GitHub Pages
        run: |
          mkdir -p out
          # Copy all HTML pages
          cp -r .next/server/pages/* out/
          # Copy Next.js assets
          cp -r .next/static/* out/_next/

      # Step 6: Upload the artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./out

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test || true
        env:
          CI: false

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      # Step 1: Download the artifact
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: github-pages
          path: ./out

      # Step 2: Configure GitHub Pages
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      # Step 3: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          path: ./out

